import type { NSCardType } from '@/types/NSCard';
import duckImage from '@/assets/duck.png';

export const SIGNAL_CARDS: NSCardType[] = [
  {
    title: '네이버 거래량 급증 감지',
    context: '장 초반 대비 거래량이 3배 이상 증가했습니다.',
    date: '2025-12-18',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '외국인 매도 집중',
    context: '외국인 순매도가 단기간 급증하고 있습니다.',
    date: '2025-12-17',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '단기 고점 형성 가능성',
    context: '기술적 지표상 단기 고점 신호가 감지되었습니다.',
    date: '2025-12-16',
    bookmarked: true,
  },
  {
    title: '이평선 이탈 발생',
    context: '주가가 주요 이동평균선을 하향 이탈했습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '프로그램 매도 전환',
    context: '프로그램 수급이 순매도로 전환되었습니다. 프로그램 수급이 순매도로 전환되었습니다.',
    date: '2025-12-14',
    bookmarked: true,
    image: duckImage,
  },

  {
    title: '호가 잔량 급감',
    context: '매수 잔량이 빠르게 감소하고 있습니다.',
    date: '2025-12-13',
    bookmarked: false,
  },
  {
    title: '장중 변동성 확대',
    context: '평균 대비 변동성이 크게 확대되었습니다.',
    date: '2025-12-12',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '단기 추세 약화',
    context: '단기 상승 추세가 둔화되는 모습입니다.',
    date: '2025-12-11',
    bookmarked: false,
  },
  {
    title: '거래대금 감소',
    context: '거래대금이 전일 대비 크게 감소했습니다.',
    date: '2025-12-10',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '저항 구간 접근',
    context: '과거 고점 부근 저항 구간에 도달했습니다.',
    date: '2025-12-09',
    bookmarked: false,
  },
  {
    title: '네이버 거래량 급증 감지',
    context: '장 초반 대비 거래량이 3배 이상 증가했습니다.',
    date: '2025-12-18',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '외국인 매도 집중',
    context: '외국인 순매도가 단기간 급증하고 있습니다.',
    date: '2025-12-17',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '단기 고점 형성 가능성',
    context: '기술적 지표상 단기 고점 신호가 감지되었습니다.',
    date: '2025-12-16',
    bookmarked: true,
  },
  {
    title: '이평선 이탈 발생',
    context: '주가가 주요 이동평균선을 하향 이탈했습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '프로그램 매도 전환',
    context: '프로그램 수급이 순매도로 전환되었습니다. 프로그램 수급이 순매도로 전환되었습니다.',
    date: '2025-12-14',
    bookmarked: true,
    image: duckImage,
  },

  {
    title: '호가 잔량 급감',
    context: '매수 잔량이 빠르게 감소하고 있습니다.',
    date: '2025-12-13',
    bookmarked: false,
  },
  {
    title: '장중 변동성 확대',
    context: '평균 대비 변동성이 크게 확대되었습니다.',
    date: '2025-12-12',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '단기 추세 약화',
    context: '단기 상승 추세가 둔화되는 모습입니다.',
    date: '2025-12-11',
    bookmarked: false,
  },
  {
    title: '거래대금 감소',
    context: '거래대금이 전일 대비 크게 감소했습니다.',
    date: '2025-12-10',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '저항 구간 접근',
    context: '과거 고점 부근 저항 구간에 도달했습니다.',
    date: '2025-12-09',
    bookmarked: false,
  },
  {
    title: '네이버 거래량 급증 감지',
    context: '장 초반 대비 거래량이 3배 이상 증가했습니다.',
    date: '2025-12-18',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '외국인 매도 집중',
    context: '외국인 순매도가 단기간 급증하고 있습니다.',
    date: '2025-12-17',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '단기 고점 형성 가능성',
    context: '기술적 지표상 단기 고점 신호가 감지되었습니다.',
    date: '2025-12-16',
    bookmarked: true,
  },
  {
    title: '이평선 이탈 발생',
    context: '주가가 주요 이동평균선을 하향 이탈했습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '프로그램 매도 전환',
    context: '프로그램 수급이 순매도로 전환되었습니다. 프로그램 수급이 순매도로 전환되었습니다.',
    date: '2025-12-14',
    bookmarked: true,
    image: duckImage,
  },

  {
    title: '호가 잔량 급감',
    context: '매수 잔량이 빠르게 감소하고 있습니다.',
    date: '2025-12-13',
    bookmarked: false,
  },
  {
    title: '장중 변동성 확대',
    context: '평균 대비 변동성이 크게 확대되었습니다.',
    date: '2025-12-12',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '단기 추세 약화',
    context: '단기 상승 추세가 둔화되는 모습입니다.',
    date: '2025-12-11',
    bookmarked: false,
  },
  {
    title: '거래대금 감소',
    context: '거래대금이 전일 대비 크게 감소했습니다.',
    date: '2025-12-10',
    bookmarked: true,
    image: duckImage,
  },
  {
    title: '저항 구간 접근',
    context: '과거 고점 부근 저항 구간에 도달했습니다.',
    date: '2025-12-09',
    bookmarked: false,
  },
];
export const NOISE_CARDS: NSCardType[] = [
  {
    title: '장중 미세 변동',
    context: '유의미하지 않은 가격 변동이 감지되었습니다.',
    date: '2025-12-18',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '단기 체결 증가',
    context: '짧은 시간 동안 체결 빈도가 증가했습니다.',
    date: '2025-12-17',
    bookmarked: true,
  },
  {
    title: '호가 변동 잦음',
    context: '호가 변동이 잦으나 추세 변화는 없습니다.',
    date: '2025-12-16',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '미약한 거래량 증가',
    context: '거래량이 소폭 증가했으나 의미는 낮습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '단기 체결 공백',
    context: '일시적인 체결 공백이 발생했습니다.',
    date: '2025-12-14',
    bookmarked: true,
  },
  {
    title: '가격 횡보 지속',
    context: '가격이 좁은 범위 내에서 횡보 중입니다.',
    date: '2025-12-13',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '미세한 수급 변화',
    context: '수급 변화가 관측되었으나 영향은 제한적입니다.',
    date: '2025-12-12',
    bookmarked: false,
  },
  {
    title: '체결 강도 변화',
    context: '체결 강도에 소폭 변화가 있습니다.',
    date: '2025-12-11',
    bookmarked: true,
  },
  {
    title: '호가 변동 잦음',
    context: '호가 변동이 잦으나 추세 변화는 없습니다.',
    date: '2025-12-16',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '미약한 거래량 증가',
    context: '거래량이 소폭 증가했으나 의미는 낮습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '단기 체결 공백',
    context: '일시적인 체결 공백이 발생했습니다.',
    date: '2025-12-14',
    bookmarked: true,
  },
  {
    title: '가격 횡보 지속',
    context: '가격이 좁은 범위 내에서 횡보 중입니다.',
    date: '2025-12-13',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '호가 변동 잦음',
    context: '호가 변동이 잦으나 추세 변화는 없습니다.',
    date: '2025-12-16',
    bookmarked: false,
    image: duckImage,
  },
  {
    title: '미약한 거래량 증가',
    context: '거래량이 소폭 증가했으나 의미는 낮습니다.',
    date: '2025-12-15',
    bookmarked: false,
  },
  {
    title: '단기 체결 공백',
    context: '일시적인 체결 공백이 발생했습니다.',
    date: '2025-12-14',
    bookmarked: true,
  },
  {
    title: '가격 횡보 지속',
    context: '가격이 좁은 범위 내에서 횡보 중입니다.',
    date: '2025-12-13',
    bookmarked: false,
    image: duckImage,
  },
];
